### PR TITLE
[mesh] Texturing: Multi-band blending

### LINKED ISSUE #644: BUG: incorrect index calculation for "bottom-right to up-left" scan in void Texturing::generateTexturesSubSet(...)
Got `Abnormal program termination: received signal 11 (SIGSEGV)` in step `[11/11] Texturing`.

I built and compiled AliceVision with vcpkg and VS 2017 (15.9.12) under Windows 10 from the lastest commit in develop branch (commit 132ac39d67b8ba9a356b6b66c245ccf0e8f59258), and ran the photogrammetry pipeline through `python bin/meshroom_photogrammetry`.

[dataset_monstree/mini3](https://github.com/alicevision/dataset_monstree/tree/master/mini3) was used.

After changing 
```
617 unsigned int yoffset = (outTextureSide - y) * outTextureSide;
...
620     unsigned int xyoffset = yoffset + (outTextureSide - x);
```

to 

```
617 unsigned int yoffset = (outTextureSide - y - 1) * outTextureSide;
...
620     unsigned int xyoffset = yoffset + (outTextureSide - x - 1);
```
in file  `${AliceVision_root}/src/aliceVision/mesh/Texturing.cpp`, the problem went away, and the generated texture seems to be correct.

### PR DESCRIPTION
**Pull request by ClaraVere**
## Description

Largely improve the texturing quality by using multi-band blending technique.

Split each input camera into frequency bands, by calculating its laplacian pyramid. For each output texture file, it computes the texture fusion per frequency bands with different number of contributions. The color averaging is now weighted by a score defined by the triangle reprojection area.
The textures per frequency bands are then combined to create the final output texture files.

## Features list

- [X] Split an image in frequency bands and reconstitute the image from its frequency bands
- [X] Add triangles contributions to a specific frequency band
- [X] Improve padding performance (2 image visit instead of 2*paddingSize)

## Implementation remarks

- [X] Add colorspace option to ImageCache
- [X] Improve colorspace option of writeImage (allow change of input colorspace)

Fix #644

### CODE REVIEW

**Comment by fabiencastan** [comment]
Move `main_multibandtest.cpp` to `samples` (instead of `software/utils`).

File: src/aliceVision/mesh/Texturing.cpp [hunk 1]
```diff
@@ -253,31 +254,45 @@ void Texturing::generateUVsBasicMethod(mvsUtils::MultiViewParams& mp)
...
                                  const boost::filesystem::path &outPath, EImageFileType textureFileType)
 {
-    mvsUtils::ImagesCache imageCache(&mp, 0);
+    ALICEVISION_LOG_INFO("Texturing: Use multiband blending with the following contributions per band:");
+    texParams.nbBand = texParams.multiBandNbContrib.size();
+    for(int c: texParams.multiBandNbContrib)
+    {
+        ALICEVISION_LOG_INFO(c << ", ");
+        if(c == 0)
+            texParams.nbBand -= 1;
```
Comment (yann-lty) [inline src/aliceVision/mesh/Texturing.cpp]: Review this: only works with if last band nbContrib is set to 0.

File: src/software/pipeline/main_texturing.cpp [hunk 2]
```diff
@@ -85,8 +85,12 @@ int main(int argc, char* argv[])
             "Texture edge padding size in pixel")
         ("flipNormals", po::value<bool>(&flipNormals)->default_value(flipNormals),
             "Option to flip face normals. It can be needed as it depends on the vertices order in triangles and the convention change from one software to another.")
-        ("maxNbImagesForFusion", po::value<int>(&texParams.maxNbImagesForFusion)->default_value(texParams.maxNbImagesForFusion),
-            "Max number of images to combine to create the final texture.")
+        ("useScore", po::value<bool>(&texParams.useScore)->default_value(texParams.useScore),
+             "Use triangles scores for multiband blending.")
```
Comment (yann-lty) [inline src/software/pipeline/main_texturing.cpp]: Not directly related to multi-band blending. 
Maybe `Use triangles scores (based on observations and re-projected areas in source images) for weighting contributions.` ?

File: src/aliceVision/mvsData/Image.hpp [hunk 3]
```diff
@@ -0,0 +1,156 @@
...
+
+#include <algorithm>
+
+namespace aliceVision {
+
+class Image
+{
+private:
+    std::vector<Color> _img;
+    int _width = 0;
```
Comment (simogasp) [inline src/aliceVision/mvsData/Image.hpp]: _width{0};  (use {} for initialization)

File: src/aliceVision/mvsData/Image.hpp [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+    int _height = 0;
+
+public:
+    Image()
```
Comment (simogasp) [inline src/aliceVision/mvsData/Image.hpp]: simply `Image() = default;`

File: src/aliceVision/mvsData/Image.hpp [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+    }
+
+    Image(int width, int height)
+        : _width(width)
+        , _height(height)
+    {
+        _img.resize(width*height);
+    }
+
+    Image(Color* data, int  width, int  height)
```
Comment (simogasp) [inline src/aliceVision/mvsData/Image.hpp]: u can chain the constructors:
```c++
Image(Color* data, int  width, int  height) : Image(width, height)
{
for(int i = 0; i < _width*_height; ++i)
            _img[i] = data[i];

}
```

File: src/aliceVision/mvsData/Image.hpp [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+    {
+        _width = param._width;
+        _height = param._height;
+        _img.resize(_width*_height);
+        _img = param._img;
+        return *this;
+    }
+
+    //outImg = inImga - inImgb
+    static void imageDiff(const Image& inImga, const Image& inImgb, Image& outImg)
```
Comment (simogasp) [inline src/aliceVision/mvsData/Image.hpp]: can be just a function and not a static member

File: src/aliceVision/mvsData/Image.hpp [hunk 7]
```diff
@@ -0,0 +1,156 @@
...
+            throw std::runtime_error("Incompatible image sizes");
+
+        outImg.resize(inImga._width, inImga._height);
+        for(int i = 0; i < inImga._width*inImga._height; ++i)
+        {
+            outImg._img[i] = inImga._img.at(i) - inImgb._img.at(i);
+        }
+    }
+
+    static void imageDownscaleDiff(Image& inImga, Image& inImgb, Image& outImg, unsigned int downscale)
```
Comment (simogasp) [inline src/aliceVision/mvsData/Image.hpp]: can be just a function and not a static member

File: src/aliceVision/mvsData/Image.hpp [hunk 8]
```diff
@@ -0,0 +1,156 @@
+// This file is part of the AliceVision project.
```
Comment (simogasp) [inline src/aliceVision/mvsData/Image.hpp]: maybe split into .cpp for the implementation

File: src/aliceVision/mesh/Texturing.cpp [hunk 9]
```diff
@@ -451,7 +451,7 @@ void Texturing::generateTexturesSubSet(const mvsUtils::MultiViewParams& mp,
                 if(contrib + 1 == nbContribLevel)
```
Comment (fabiencastan) [inline src/aliceVision/mesh/Texturing.cpp]: Simpler and avoid to access outside of the array.
```
if(contrib + 1 == texParams.multiBandNbContrib[band])
{
    ++band;
}
```
So we could remove the variable `nbContribLevel`.

File: src/aliceVision/mesh/Texturing.cpp [hunk 10]
```diff
@@ -451,7 +451,7 @@ void Texturing::generateTexturesSubSet(const mvsUtils::MultiViewParams& mp,
...
                 {
```
Comment (fabiencastan) [inline src/aliceVision/mesh/Texturing.cpp]: Few lines above, we have:
`int nbContribMax = std::min(texParams.multiBandNbContrib.back(), static_cast<int>(scorePerCamId.size()));`

I think yes, but just to be sure: Does `texParams.multiBandNbContrib` still contains cumulative values in the latest version?

File: src/aliceVision/mesh/Texturing.cpp [hunk 11]
```diff
@@ -259,17 +259,22 @@ void Texturing::generateTextures(const mvsUtils::MultiViewParams &mp,
                                  const boost::filesystem::path &outPath, EImageFileType textureFileType)
 {
     ALICEVISION_LOG_INFO("Texturing: Use multiband blending with the following contributions per band:");
+
```
Comment (fabiencastan) [inline src/aliceVision/mesh/Texturing.cpp]:
```
{
    // Ensure that contribution levels do not contain 0 and are sorted (as they represent cumulative values).
    auto& m = texParams.multiBandNbContrib;
    m.erase(std::remove(std::begin(m), std::end(m), 0), std::end(m));
    texParams.nbBand = m.size();

    if(!std::is_sorted(std::begin(m), std::end(m)))
    {
        ALICEVISION_LOG_INFO("Sorting contributions per band (necessary).");
        std::sort(std::begin(m), std::end(m));
    }
}
```

File: src/samples/CMakeLists.txt [hunk 12]
```diff
@@ -10,7 +10,6 @@ add_subdirectory(featuresRepeatability)
 # add_subdirectory(imageData)
 add_subdirectory(imageDescriberMatches)
 add_subdirectory(kvldFilter)
-add_subdirectory(multiBandBlending)
```
Comment (fabiencastan) [inline src/samples/CMakeLists.txt]: Looks like a mistake as the sample itself is not removed...

File: src/aliceVision/CMakeLists.txt [hunk 13]
```diff
@@ -38,7 +38,6 @@ endif()
 # MVS modules
 
 if(ALICEVISION_BUILD_MVS)
-  add_subdirectory(imageIO)
```
Comment (fabiencastan) [inline src/aliceVision/CMakeLists.txt]: We tried to keep a split between IO and data structures as almost all modules have dependencies to data structures.
So if we don't split it, all modules will have dependencies to IO.

But maybe this commit is a needed intermediate solution before a new change? If not, we do not want to merge mvsData and imageIO.

File: src/aliceVision/mesh/Texturing.cpp [hunk 14]
```diff
@@ -481,11 +481,9 @@ void Texturing::generateTexturesSubSet(const mvsUtils::MultiViewParams& mp,
         }
         ALICEVISION_LOG_INFO("- camera " << camId + 1 << "/" << mp.ncams << " with contributions to " << cameraContributions.size() << " texture files:");
 
+        //Load camera image from cache
         imageCache.refreshData(camId);        
-
-        //conversion ImagesCache::Img -> Image
-        mvsUtils::ImagesCache::ImgPtr imgPtr = imageCache.getImg_sync(camId);
-        Image camImg(imgPtr->data, imgPtr->getWidth(), imgPtr->getHeight());
+        const Image& camImg = *(imageCache.getImg_sync(camId));
```
Comment (fabiencastan) [inline src/aliceVision/mesh/Texturing.cpp]: `getImg_sync` returns an `ImgPtr` which is a `std::shared_ptr`.
If you remove the temporary variable and directly get the value from the shared_ptr, the shared_ptr ownership is removed.

File: src/aliceVision/mesh/Texturing.hpp [hunk 15]
```diff
@@ -152,24 +152,24 @@ struct Texturing
     // Create buffer for the set of output textures
     struct AccuImage
     {
-        std::vector<Color> img;
+        Image img;
```
Comment (fabiencastan) [inline src/aliceVision/mesh/Texturing.hpp]: +1

File: src/aliceVision/mvsUtils/ImagesCache.hpp [hunk 16]
```diff
@@ -21,48 +22,11 @@ namespace mvsUtils {
 
 class ImagesCache
 {
-public:
-    class Img
```
Comment (fabiencastan) [inline src/aliceVision/mvsUtils/ImagesCache.hpp]: +1

File: src/aliceVision/CMakeLists.txt (hunk 13 above)
Comment (yann-lty) [reply src/aliceVision/CMakeLists.txt]: We have a several files related to image IO:
- image/io.hpp   `// SfM: functions to read/writes images`
- imageIO/image.hpp  `// MVS: functions to read/write images, relies on mvsData for data structure types (rgb, Color and now Image)`
- mvsData/imageIO.hpp (image.hpp on develop) `// MVS: containing EImageFileType enum`

The idea was to start simplifying things. We will probably want to merge image types and IO at some point, but it already seems weird to have, for the MVS part, this split between `imageIO/image.hpp` and `mvsData/imageIO.hpp`. And everything that uses mvsData also uses imageIO, so the merge does not seem that problematic IMHO. But if we want to keep this `imageIO` module as the one that will stay, maybe it could be the other way around: move what's inside mvsData/imageIO.hpp into the imageIO module.

File: src/aliceVision/mvsUtils/MultiViewParams.cpp [hunk 17]
```diff
@@ -511,21 +511,36 @@ double MultiViewParams::getCamsMinPixelSize(const Point3d& x0, StaticVector<int>
...
-bool MultiViewParams::isPixelInImage(const Pixel& pix, int d, int camId) const
+bool MultiViewParams::isPixelInSourceImage(const Pixel& pixRC, int camId, int margin) const
 {
-    return ((pix.x >= d) && (pix.x < getWidth(camId) - d) && (pix.y >= d) && (pix.y < getHeight(camId) - d));
+    const IndexT viewId = getViewId(camId);
+    const sfmData::View& view = *(_sfmData.getViews().at(viewId));
+    const camera::IntrinsicBase* intrinsicPtr = _sfmData.getIntrinsicPtr(view.getIntrinsicId());
+
+    Vec2 pix_disto = intrinsicPtr->get_d_pixel({pixRC.x, pixRC.y});
+    return isPixelInImage(Pixel(pix_disto.x(), pix_disto.y()), camId, margin);
```
Comment (fabiencastan) [inline src/aliceVision/mvsUtils/MultiViewParams.cpp]: All the MVS structures have a global downscale (backed in all matrices, etc.) but it's not the case for the sfmData which contains the original SfM.
So we need to compensate for that:
```
const double s = getDownscaleFactor(camId);
const Vec2 pix_disto = intrinsicPtr->get_d_pixel({pixRC.x * s, pixRC.y * s}) / s;
```

File: src/aliceVision/mesh/Texturing.cpp [hunk 18]
```diff
@@ -482,8 +482,9 @@ void Texturing::generateTexturesSubSet(const mvsUtils::MultiViewParams& mp,
         ALICEVISION_LOG_INFO("- camera " << camId + 1 << "/" << mp.ncams << " with contributions to " << cameraContributions.size() << " texture files:");
 
         //Load camera image from cache
-        imageCache.refreshData(camId);        
-        const Image& camImg = *(imageCache.getImg_sync(camId));
+        imageCache.refreshData(camId);
+        mvsUtils::ImagesCache::ImgPtr imgPtr = imageCache.getImg_sync(camId);
```
Comment (fabiencastan) [inline src/aliceVision/mesh/Texturing.cpp]: `mvsUtils::ImagesCache::ImgPtr imgPtr = imageCache.getImg_sync(camId); // keep ownership`

Comment (fabiencastan) [reply src/aliceVision/mesh/Texturing.cpp]: It would be good to rename `ImgPtr` into `ImgSharedPtr`.

File: src/aliceVision/mvsData/imageIO.hpp [hunk 19]
```diff
@@ -31,6 +42,30 @@ enum class EImageColorSpace
...
+    }
+    /// @brief Assumes that @p from is LINEAR
+    OutputFileColorSpace(EImageColorSpace to_)
+    {
+        if(to_ == EImageColorSpace::NO_CONVERSION)
+            to = from;
+        else
+            to = to_;
+    }
+    OutputFileColorSpace()
```
Comment (simogasp) [inline src/aliceVision/mvsData/imageIO.hpp]: = default;

File: src/aliceVision/mvsData/imageIO.cpp [hunk 20]
```diff
@@ -294,29 +379,34 @@ void writeImage(const std::string& path,
     fs::rename(tmpPath, path);
 }
 
-void writeImage(const std::string& path, int width, int height, const std::vector<unsigned char>& buffer, EImageQuality imageQuality, EImageColorSpace imageColorSpace, const oiio::ParamValueList& metadata)
+void writeImage(const std::string& path, int width, int height, const std::vector<unsigned char>& buffer, EImageQuality imageQuality, OutputFileColorSpace colorspace, const oiio::ParamValueList& metadata)
```
Comment (simogasp) [inline src/aliceVision/mvsData/imageIO.cpp]: const OutputFileColorSpace& colorspace

File: src/aliceVision/mvsData/imageIO.cpp [hunk 21]
```diff
@@ -238,7 +323,7 @@ void writeImage(const std::string& path,
                 int nchannels,
                 const std::vector<T>& buffer,
                 EImageQuality imageQuality,
-                EImageColorSpace imageColorSpace,
+                OutputFileColorSpace colorspace,
```
Comment (simogasp) [inline src/aliceVision/mvsData/imageIO.cpp]: const OutputFileColorSpace& colorspace

File: src/aliceVision/mvsData/imageIO.hpp [hunk 22]
```diff
@@ -31,6 +42,30 @@ enum class EImageColorSpace
   NO_CONVERSION
 };
 
+
+struct OutputFileColorSpace
+{
+    EImageColorSpace from = EImageColorSpace::LINEAR;
```
Comment (simogasp) [inline src/aliceVision/mvsData/imageIO.hpp]: EImageColorSpace from{EImageColorSpace::LINEAR};
EImageColorSpace to{EImageColorSpace::AUTO};

File: src/aliceVision/mvsUtils/ImagesCache.cpp [hunk 23]
```diff
@@ -61,6 +60,14 @@ void ImagesCache::initIC( std::vector<std::string>& _imagesNames )
...
 
+void ImagesCache::setCacheSize(int nbPreload)
+{
+    N_PRELOADED_IMAGES = nbPreload;
+    imgs.resize(N_PRELOADED_IMAGES);
+    mapIdCamId.resize( N_PRELOADED_IMAGES, -1 );
+    mapIdClock.resize( N_PRELOADED_IMAGES, clock() );
+}
+
 ImagesCache::~ImagesCache()
```
Comment (simogasp) [inline src/aliceVision/mvsUtils/ImagesCache.cpp]: = default

**Comment by fabiencastan** [comment]
LGTM!
