### PR TITLE
Fixes #1202: Added an available memory check to constrain the number of CPU c…

### LINKED ISSUE #1202: Alicevision build (docker or otherwise) has a memory issue while building, and crashes the system
When building alicevision using cmake, the default docker script uses all threads of the CPU when building, which while fast, can use more memory than the system can provide. So, on systems with low memory, this can crash the system, often going back to the login screen of the desktop environment.

The fix here is to check the free memory on the system, and to set  number of cmake jobs to 1 job per gigabyte of free memory. This allows alicevision to build the docker images required.

### PR DESCRIPTION
**Pull request by sanchayanghosh**
…ores used, and moved fetch.sh call inside a dockerfile, to allowe building inside docker without having to install cmake externally.

## Description

A fix for #1202 - Here, I put a pre-condition check on the available memory on the system. 

This will usually be the memory available to the individual docker. However, since we are using an overlay system, with no specific memory caps/ caps on CPU shares, we should be seeing the state of the entire system.

## Features list

Fix #1202 - AliceVision would crash the linux environment because it exceeds the available memory when building.

## Implementation remarks

During the actual build, I found that putting 2 GB per job was ideal. 1GB per job would crash the system.

In the worst case, we have an nproc/2 situation, which anyhow is the default behaviour of cmake.

### CODE REVIEW

File: docker/build-ubuntu.sh [hunk 1]
```diff
@@ -10,7 +10,6 @@ test -z "$AV_VERSION" && AV_VERSION="$(git rev-parse --abbrev-ref HEAD)-$(git re
 test -z "$CUDA_VERSION" && CUDA_VERSION=11.0
 test -z "$UBUNTU_VERSION" && UBUNTU_VERSION=20.04
 
-./docker/fetch.sh
```
Comment (fabiencastan) [inline docker/build-ubuntu.sh:13]: why did you remove that?

Comment (fabiencastan) [reply docker/build-ubuntu.sh:13]: ah ok, moved in deps file.

Comment (sanchayanghosh) [reply docker/build-ubuntu.sh:13]: correct. i moved it to deps file.

File: docker/check-cpu.sh [hunk 2]
```diff
@@ -0,0 +1,16 @@
+#!/bin/sh
+
```
Comment (fabiencastan) [inline docker/check-cpu.sh:2]: It would be good to add few lines of comments here to explain the goal of this file.

File: docker/Dockerfile_ubuntu_deps [hunk 3]
```diff
@@ -43,17 +43,37 @@ RUN . ./etc/os-release && \
...
 
-COPY dl/deps ${AV_BUILD}/external/download/
+WORKDIR ${AV_DEV}
+
+COPY docker ${AV_DEV}/docker/
+
+RUN ls ${AV_DEV}/docker
+
+RUN pwd
+
```
Comment (fabiencastan) [inline docker/Dockerfile_ubuntu_deps:69]:
```suggestion
```

File: docker/Dockerfile_ubuntu [hunk 4]
```diff
@@ -53,7 +55,7 @@ RUN cmake -DCMAKE_BUILD_TYPE=Release \
         -DALICEVISION_BUILD_DOC:BOOL=OFF \
         -DALICEVISION_BUILD_EXAMPLES:BOOL=OFF \
         "${AV_DEV}" && \
-    make install -j"$(nproc)" && \
+    make install -j$((${CPU_CORES}/2)) && \
```
[the remark this answers is not in the document]
Comment (sanchayanghosh) [reply docker/Dockerfile_ubuntu:58]: I also have no problem with this. But, the reason why I put 1GB per process in check-cpu.sh was that when building dependencies, I am providing 1GB per process, because I didn't notice any crashes when building dependencies, but only during actually building AliceVision itself.

Also, if we build dependencies with a buffer of 2GB per CPU core, the dependencies can take time to build.

If it is okay then I can make the change.

[the remark this answers is not in the document]
Comment (sanchayanghosh) [reply docker/Dockerfile_ubuntu]: On a closer look, 2GB per process seems fine. This is because, in the worst case (that is if no of processes are lower than available memory), the system anyhow builds with nproc/2, which is the default parameters that cmake builds with. 

c2c6e25855bb8f929864a41ffa9a4635ad28e18 implements the change.

File: docker/check-cpu.sh (hunk 2 above)
Comment (sanchayanghosh) [reply docker/check-cpu.sh:2]: https://github.com/alicevision/AliceVision/commit/5c2c6e25855bb8f929864a41ffa9a4635ad28e18

contains the commit where I have given an exposition of the utility of the file.

**Comment by fabiencastan** [comment]
Could you apply the same change to use ${CPU_CORES} in the docker centos too?

File: docker/check-cpu.sh (hunk 2 above)
Comment (fabiencastan) [reply docker/check-cpu.sh:2]: Thanks!

File: docker/check-cpu.sh [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+# This script is used to check the amount of available memory and restricts the number of concurrent jobs/processes (-j${CPU_CORES}) used
+# to 1 GB per process. If the number of processes are less than the amount of available memory (considering 2GB per core) we restrict the number
+# of cores to the total number of cores present on the system.
```
Comment (fabiencastan) [inline docker/check-cpu.sh:5]:
```suggestion
# This script is used to check the amount of available memory to ensure 2 GB of memory per process.
# If the number of processes is greater than the amount of available memory (considering 2 GB per core) we restrict the number of cores to use.
#
# Sample usage:
# CPU_CORES=`check-cpu.sh`
# make -j${CPU_CORES}
```

**Comment by sanchayanghosh** [comment]
> 

Hi. I could make the same change. I was just testing the build ability of the docker container and I recently validated the configuration on github actions as well. In a new commit, I shall apply the CPU_CHECK for centos as well

File: docker/check-cpu.sh [hunk 6]
```diff
@@ -0,0 +1,24 @@
...
+' | sed "s/Gi//")
+
+
+
+test ${FREE_MEM} -ge 2 || FREE_MEM=$((${FREE_MEM} + 2))
+
+
+test ${FREE_MEM} -lt $(nproc) || FREE_MEM=$(nproc)
+
+echo $((${FREE_MEM}/2))
```
Comment (fabiencastan) [inline docker/check-cpu.sh:24]:
```suggestion
NPROC=$(nproc)

FREE_MEM=$(free -g | grep Mem | awk '
{
print $7
}
' | sed "s/Gi//")

# Arbitrary minimum of RAM per process
MIN_RAM_PER_CORE=2

# The number of processes we can run in parallel to guarantee at least N GB of RAM per process
MAX_CORES_RAM=$((${FREE_MEM} / ${MIN_RAM_PER_CORE}))

# Maximum usable cores regarding the number of available cores and the amount of available memory
USABLE_CORES=$((${MAX_CORES_RAM} < ${NPROC} ? ${MAX_CORES_RAM} : ${NPROC}))

# echo "NPROC=${NPROC}"
# echo "FREE_MEM=${FREE_MEM}"
# echo "MIN_RAM_PER_CORE=${MIN_RAM_PER_CORE}"
# echo "MAX_CORES_RAM=${MAX_CORES_RAM}"
# echo " => USABLE_CORES=${USABLE_CORES}"
# echo ""

echo ${USABLE_CORES}
```

File: docker/Dockerfile_ubuntu_deps [hunk 7]
```diff
@@ -43,17 +43,37 @@ RUN . ./etc/os-release && \
...
+RUN ./docker/fetch.sh
```
Comment (fabiencastan) [inline docker/Dockerfile_ubuntu_deps]: I'm not sure it's a good idea to move the download of the dependencies in the dockerfile or not. What are the advantages to do that?

In all case, it's a bit unrelated to the original PR goal and should at least be done in a separated commit as it's a different feature. I cannot merge the cpu checks for now due to that.

Comment (fabiencastan) [reply docker/Dockerfile_ubuntu_deps]: If we put the download in the docker, we cannot cache the download itself, it will be invalidated if we change something in the dockerfile.

Comment (sanchayanghosh) [reply docker/Dockerfile_ubuntu_deps]: I understand the problem with moving the download into docker. 

The reason I put fetch.sh into the dockerfile initially was that the user machine would end up requiring cmake in order to run fetch.sh. But I have another solution that I can implement in a different PR. 

I can make the fetch.sh run inside docker with the same uid as the running user. And then mount the current directory as a volume inside of the cmake container (let's say). This will allow us to cache the file, and the user will only need docker to run the build, no other dependencies.

Comment (sanchayanghosh) [reply docker/Dockerfile_ubuntu_deps]: > If we put the download in the docker, we cannot cache the download itself, it will be invalidated if we change something in the dockerfile.

I will remove the changes now, and only put the cpu-check.sh changes.

Comment (fabiencastan) [reply docker/Dockerfile_ubuntu_deps]: Thanks !
Btw, could you do the same modification for centos dockerfile?

Comment (sanchayanghosh) [reply docker/Dockerfile_ubuntu_deps]: Done

Comment (fabiencastan) [reply docker/Dockerfile_ubuntu_deps]: Thanks!!

File: docker/check-cpu.sh [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+# If the number of processes is greater than the amount of available memory (considering 2 GB per core) we restrict the number of cores to use.
+#
+# Sample usage:
+# CPU_CORES=`check-cpu.sh`
+# make -j${CPU_CORES}
+
+
+NPROC=$(nproc)
+
+FREE_MEM=$(free -g | grep Mem | awk '
```
Comment (predat) [inline docker/check-cpu.sh:13]: `FREE_RAM=$(awk '/^MemAvailable:/{printf("%d",$2/1024/1024)}' /proc/meminfo)
`

File: docker/check-cpu.sh [hunk 9]
```diff
@@ -0,0 +1,46 @@
...
+USABLE_CORES=$((${PRACTICAL_MAX_CORES_RAM} < ${NPROC} ? ${PRACTICAL_MAX_CORES_RAM} : ${NPROC}))
+
+# echo "NPROC=${NPROC}"
+# echo "FREE_MEM=${FREE_MEM}"
+# echo "MIN_RAM_PER_CORE=${MIN_RAM_PER_CORE}"
+# echo "MAX_CORES_RAM=${MAX_CORES_RAM}"
+# echo " => USABLE_CORES=${USABLE_CORES}"
+# echo ""
+
+echo ${USABLE_CORES}
```
Comment (predat) [inline docker/check-cpu.sh:46]: Do not ouput trailing newline:
`echo -n ${USABLE_CORES}`

File: docker/check-cpu.sh (hunk 8 above)
Comment (fabiencastan) [reply docker/check-cpu.sh:13]: @sanchayanghosh What do you think?

File: docker/check-cpu.sh [hunk 10]
```diff
@@ -0,0 +1,46 @@
...
+# make -j${CPU_CORES}
+
+
+NPROC=$(nproc)
+
+FREE_MEM=$(free -g | grep Mem | awk '
+{
+print $7
+}
+' | sed "s/Gi//")
```
Comment (fabiencastan) [inline docker/check-cpu.sh:17]:
```suggestion
FREE_RAM=$(awk '/^MemAvailable:/{printf("%d",$2/1024/1024)}' /proc/meminfo)
```

File: docker/check-cpu.sh (hunk 9 above)
Comment (fabiencastan) [inline docker/check-cpu.sh:46]:
```suggestion
echo -n ${USABLE_CORES}
```

**Review by fabiencastan — APPROVED** [review]
